### ISSUE TITLE
CSS path wrong for child pages

### ISSUE THREAD

**Issue by emiloberg** [robinrendle/react-css-modules-boilerplate#1]
This repository creates 1 css file and multiple html files. 

Looking at `build/about/index.html` it is trying to fetch a `styles.css` from the same directory as itself, however, the css is to be found on the root level.

`about/index.html` reads: 

```
<link rel="stylesheet" href="styles.css"/>
```

where it should read

```
<link rel="stylesheet" href="../styles.css"/>
```

or possibly (but not as good as it'll not work if you're deploying the files in a sub-location on a domain):

```
<link rel="stylesheet" href="/styles.css"/>
```

**Comment by robinrendle** [comment]
@emiloberg Since I’ve just updated this project to use BrowserSync that’s no longer an issue. See #2

**Comment by emiloberg** [comment]
How is this no longer an issue?  Sure it'll work in _development_ mode, but not when building for production.

**Comment by ariesshrimp** [comment]
I understand this is closed, but I recently reached out on twitter with this same question. If the build process can't generate href's dynamically that point at the correct css file from arbitrary points down the build hierarchy, I don't see how to deploy any site you generate this way.

One solution is to ditch the directory structure and serve `/about.html`, rather than `/about/index.html`. The url really sucks, but it's a pretty small price to pay for static generated sites written using css modules. I feel like there should be a better solution.

The natural one - to use style-loader to inject different style tags into the head of each generated html page, is not trivial. style-loader depends on `window` to inject the tag, so there's not an obvious way to get it working. 😖
